import {
  Calculator,
  Heart,
  Home,
  GraduationCap,
  Briefcase,
  Percent,
  Calendar,
  Scale,
} from "lucide-react";

export const categories = [
  {
    id: 1,
    slug: "matematica",
    title: "Matemática",
    description: "Cálculos matemáticos, regra de três, porcentagem e muito mais.",
    icon: Calculator,
    color: "bg-blue-500",
  },
  {
    id: 2,
    slug: "financeiras",
    title: "Financeiras",
    description: "Juros, financiamentos, investimentos e crédito.",
    icon: Percent,
    color: "bg-green-500",
  },
  {
    id: 3,
    slug: "saude",
    title: "Saúde",
    description: "IMC, peso ideal, calorias, TMB e diversas calculadoras.",
    icon: Heart,
    color: "bg-red-500",
  },
  {
    id: 4,
    slug: "construcao",
    title: "Construção",
    description: "Concreto, pisos, tinta, tijolos e materiais.",
    icon: Home,
    color: "bg-yellow-500",
  },
  {
    id: 5,
    slug: "educacao",
    title: "Educação",
    description: "Notas, médias, frequência e desempenho escolar.",
    icon: GraduationCap,
    color: "bg-purple-500",
  },
  {
    id: 6,
    slug: "trabalhistas",
    title: "Trabalhistas",
    description: "FGTS, férias, rescisão, salário líquido e benefícios.",
    icon: Briefcase,
    color: "bg-orange-500",
  },
  {
    id: 7,
    slug: "datas",
    title: "Datas",
    description: "Diferença entre datas, idade e contagem de dias.",
    icon: Calendar,
    color: "bg-pink-500",
  },
  {
    id: 8,
    slug: "conversores",
    title: "Conversores",
    description: "Moedas, medidas, temperatura, peso e unidades.",
    icon: Scale,
    color: "bg-cyan-500",
  },
];